sudo: false
language: android

env:
  global:
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

android:
  components:
    - build-tools-25.0.3
    - tools
    - platform-tools
    - android-25
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licenses:
    - 'android-sdk-license-.+'
    - '.+'
    
script:
  - ./gradlew build assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
  
notifications:
  email: false
