package com.gautamastudios.whatweather.storage.model;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

/**
 * The alerts array contains objects representing the severe weather warnings issued for the requested location by a
 * governmental authority (please see our @see <a href="https://darksky.net/dev/docs/sources">data
 * sources page</a> for a list of sources). Objects in the alerts array contain the following properties:
 * <p>
 * {@link Alert#description} required
 * A detailed description of the alert.
 * <p>
 * {@link Alert#expires} optional
 * The UNIX time at which the alert will expire. (Some alerts sources, unfortunately, do not define expiration time,
 * and in these cases this parameter will not be defined.)
 * <p>
 * {@link Alert#regions} required
 * A json array of strings representing the names of the regions covered by this weather alert. This data type needs
 * to be deserialized to a java object.
 * <p>
 * {@link Alert#severity} required
 * The severity of the weather alert. Will take one of the following values: "advisory" (an individual should be
 * aware of potentially severe weather), "watch" (an individual should prepare for potentially severe weather), or
 * "warning" (an individual should take immediate action to protect themselves and others from potentially severe
 * weather).
 * <p>
 * {@link Alert#time} required
 * The UNIX time at which the alert was issued.
 * <p>
 * {@link Alert#title} required
 * A brief description of the alert.
 * <p>
 * {@link Alert#uri} required
 * An HTTP(S) URI that one may refer to for detailed information about the alert.
 */
@Entity(tableName = "alert")
public class Alert {

    @PrimaryKey(autoGenerate = true)
    private int autoGeneratedKey;

    @ColumnInfo(name = "description")
    private String description;

    @ColumnInfo(name = "expires")
    private long expires;

    @ColumnInfo(name = "regions")
    private String regions;

    @ColumnInfo(name = "severity")
    private String severity;

    @ColumnInfo(name = "time")
    private long time;

    @ColumnInfo(name = "title")
    private String title;

    @ColumnInfo(name = "uri")
    private String uri;

    public Alert(int autoGeneratedKey, String description, long expires, String regions, String severity, long time,
            String title, String uri) {
        this.autoGeneratedKey = autoGeneratedKey;
        this.description = description;
        this.expires = expires;
        this.regions = regions;
        this.severity = severity;
        this.time = time;
        this.title = title;
        this.uri = uri;
    }

    public int getAutoGeneratedKey() {
        return autoGeneratedKey;
    }

    public String getDescription() {
        return description;
    }

    public long getExpires() {
        return expires;
    }

    public String getRegions() {
        return regions;
    }

    public String getSeverity() {
        return severity;
    }

    public long getTime() {
        return time;
    }

    public String getTitle() {
        return title;
    }

    public String getUri() {
        return uri;
    }
}
