package com.gautamastudios.whatweather.storage.model;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * A data block object represents the various weather phenomena occurring over a period of time. Such objects contain
 * the following properties:
 * <p>
 * {@link DataBlock#data} required <br>
 * An array of {@link DataPoint}, ordered by time, which together describe the
 * weather conditions at the requested location over time.
 * <p>
 * {@link DataBlock#summary} optional <br>
 * A human-readable summary of this data block.
 * <p>
 * {@link DataBlock#icon} optional <br>
 * A machine-readable text summary of this data block. (May take on the same values as the icon property of
 * {@link DataPoint}.)
 */
@Entity(tableName = "datablock")
public class DataBlock {

    public static final String FIELD_DATA_BLOCK_TYPE = "data_block_type";

    @PrimaryKey(autoGenerate = true)
    private int autoGeneratedID;

    @Ignore
    @SerializedName("data")
    private List<DataPoint> data;

    @ColumnInfo(name = "summary")
    private String summary;

    @ColumnInfo(name = "icon")
    private String icon;

    @ColumnInfo(name = FIELD_DATA_BLOCK_TYPE)
    private int type;

    public void setDataBlockType(@DataPointType int type) {
        this.type = type;
    }

    public DataBlock(int autoGeneratedID, String summary, String icon, int type) {
        this.autoGeneratedID = autoGeneratedID;
        this.summary = summary;
        this.icon = icon;
        this.type = type;
    }

    public int getAutoGeneratedID() {
        return autoGeneratedID;
    }

    public List<DataPoint> getData() {
        return data;
    }

    public List<DataPoint> getData(@DataPointType int type) {
        if (data == null) {
            return new ArrayList<>();
        }

        for (DataPoint dataPoint : data) {
            dataPoint.setDataPointType(type);
        }
        return data;
    }

    public String getSummary() {
        return summary;
    }

    public String getIcon() {
        return icon;
    }

    public void setData(List<DataPoint> dataPoints) {
        this.data = dataPoints;
    }

    public int getType() {
        return type;
    }
}
